# Generated by Django 5.2.3 on 2025-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
